# Generated by Django 6.1 on 2026-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_tente', models.CharField(help_text='Téléphone ou email tenté au moment du login', max_length=255)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('reussie', models.BooleanField(default=False)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-date_tentative'],
                'indexes': [models.Index(fields=['identifiant_tente', 'date_tentative'], name='platform_ad_identif_d4c78a_idx'), models.Index(fields=['adresse_ip', 'date_tentative'], name='platform_ad_adresse_24da67_idx')],
            },
        ),
    ]
