from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.employee_login, name="login"),
    path("logout/", views.employee_logout, name="logout"),
    path("pompiste/", views.pompiste_accueil, name="pompiste_accueil"),
    path("pompiste/caisse/", views.pompiste_caisse, name="pompiste_caisse"),
    path("pompiste/paiement/", views.pompiste_ajouter_paiement, name="pompiste_ajouter_paiement"),
    path("pompiste/finaliser/", views.pompiste_finaliser, name="pompiste_finaliser"),
    path("pompiste/recu/<int:session_id>/", views.pompiste_recu, name="pompiste_recu"),
    path("pompiste/historique/", views.pompiste_historique, name="pompiste_historique"),
    path("pompiste/historique-pv/", views.pompiste_historique_pv, name="pompiste_historique_pv"),
    path("pompiste/pv/<int:session_id>/", views.pompiste_pv_detail, name="pompiste_pv_detail"),
    path("pv/<int:session_id>/pdf/", views.telecharger_pv_pdf, name="telecharger_pv_pdf"),
    path("gerant/", views.gerant_accueil, name="gerant_accueil"),
    path("gerant/jauge/", views.gerant_jauge, name="gerant_jauge"),
    path("gerant/depotage/", views.gerant_depotage, name="gerant_depotage"),
    path("gerant/depense/", views.gerant_depense, name="gerant_depense"),
    path("gerant/depot-bancaire/", views.gerant_depot_bancaire, name="gerant_depot_bancaire"),
    path("gerant/releve/<int:pompiste_id>/", views.gerant_releve_pompiste, name="gerant_releve_pompiste"),
    path("gerant/finaliser/<int:pompiste_id>/", views.gerant_finaliser, name="gerant_finaliser"),
    path("gerant/confronter/<int:pompiste_id>/", views.gerant_confronter, name="gerant_confronter"),
    path("admin/", views.admin_accueil, name="admin_accueil"),
    path("admin/carburants-prix/", views.admin_carburants_prix, name="admin_carburants_prix"),
    path("admin/carburants-prix/<int:station_id>/modifier/", views.admin_prix_modifier, name="admin_prix_modifier"),
    path("admin/stocks/", views.admin_stocks, name="admin_stocks"),
    path("admin/stations/", views.admin_stations, name="admin_stations"),
    path("admin/stations/creer/", views.admin_station_creer, name="admin_station_creer"),
    path("admin/stations/<int:station_id>/", views.admin_station_detail, name="admin_station_detail"),
    path("admin/stations/<int:station_id>/toggle-actif/", views.admin_station_toggle_actif, name="admin_station_toggle_actif"),
    path("admin/stations/<int:station_id>/gerer/", views.admin_station_gerer, name="admin_station_gerer"),
    path("admin/stations/<int:station_id>/supprimer/", views.admin_station_supprimer, name="admin_station_supprimer"),
    path("admin/stations/<int:station_id>/pompes/creer/", views.admin_pompe_creer, name="admin_pompe_creer"),
    path("admin/stations/<int:station_id>/historique/", views.admin_station_historique, name="admin_station_historique"),
    path("admin/stations/<int:station_id>/depenses/", views.admin_station_depenses, name="admin_station_depenses"),
    path("admin/stations/<int:station_id>/jauges/", views.admin_station_jauges, name="admin_station_jauges"),
    path("admin/stations/<int:station_id>/cuves/", views.admin_station_cuves, name="admin_station_cuves"),
    path("admin/stations/<int:station_id>/cuves/creer/", views.admin_cuve_creer, name="admin_cuve_creer"),
    path("admin/cuves/<int:cuve_id>/gerer/", views.admin_cuve_gerer, name="admin_cuve_gerer"),
    path("admin/pompes/<int:pompe_id>/gerer/", views.admin_pompe_gerer, name="admin_pompe_gerer"),
    path("admin/pompes/<int:pompe_id>/supprimer/", views.admin_pompe_supprimer, name="admin_pompe_supprimer"),
    path("admin/employes/", views.admin_employes, name="admin_employes"),
    path("admin/employes/creer/", views.admin_employe_creer, name="admin_employe_creer"),
    path("admin/employes/<int:employee_id>/toggle-actif/", views.admin_employe_toggle_actif, name="admin_employe_toggle_actif"),
    path("admin/employes/<int:employee_id>/gerer/", views.admin_employe_gerer, name="admin_employe_gerer"),
    path("admin/employes/<int:employee_id>/historique/", views.admin_employe_historique, name="admin_employe_historique"),
    path("admin/employes/<int:employee_id>/supprimer/", views.admin_employe_supprimer, name="admin_employe_supprimer"),
]
