# Generated by Django 6.1 on 2026-08-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin', '0002_superadmin'),
        ('tenants', '0005_societe_marge_tolerance_ecart_carburant_mensuel_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: INV-2026-000123', max_length=50, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, help_text="Taux de TVA applique a cette facture (%), fige a l'emission.", max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('impayee', 'Impayee'), ('partiellement_payee', 'Partiellement payee'), ('payee', 'Payee'), ('void', 'Annulee (void)')], default='impayee', max_length=20)),
                ('date_emission', models.DateTimeField()),
                ('date_echeance', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.societe')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Peut etre inferieur au montant_ttc de la facture (paiement partiel).', max_digits=12)),
                ('methode', models.CharField(choices=[('virement', 'Virement bancaire'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('paydunya', 'PayDunya')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Reference libre, optionnelle.', max_length=100)),
                ('date_paiement', models.DateTimeField(help_text='Moment reel du paiement (modifiable). A ne jamais confondre avec date_creation.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Horodatage technique de la saisie en base (audit uniquement).')),
                ('enregistre_par', models.ForeignKey(help_text='Le Super Admin qui a enregistre ce paiement manuellement.', on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to='platform_admin.superadmin')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.invoice')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_stations_min', models.PositiveIntegerField(help_text='Borne basse du palier (inclusive).')),
                ('nombre_stations_max', models.PositiveIntegerField(blank=True, help_text='Borne haute du palier (inclusive). Null = illimite vers le haut (dernier palier).', null=True)),
                ('duree_mois', models.PositiveSmallIntegerField(choices=[(1, '1 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')])),
                ('prix_par_station_mensuel', models.DecimalField(decimal_places=2, help_text='Prix unitaire mensuel par station, en FCFA.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Palier tarifaire',
                'verbose_name_plural': 'Paliers tarifaires',
                'ordering': ['nombre_stations_min', 'duree_mois'],
                'unique_together': {('nombre_stations_min', 'nombre_stations_max', 'duree_mois')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_stations', models.PositiveIntegerField(help_text='Nombre de stations actuel de la societe. Mutable : mis a jour a chaque changement (ajout/retrait de station).')),
                ('duree_mois', models.PositiveSmallIntegerField(choices=[(1, '1 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')], help_text="Duree d'engagement du cycle en cours. Fige jusqu'au renouvellement.")),
                ('montant_mensuel', models.DecimalField(decimal_places=2, help_text='nombre_stations x prix_par_station_mensuel du tier. Mutable, recalcule a chaque changement de nombre_stations.', max_digits=12)),
                ('statut', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('late', 'En retard'), ('suspended', 'Suspendu'), ('terminated', 'Resilie')], default='trial', max_length=20)),
                ('date_debut', models.DateTimeField(help_text="Debut du cycle d'engagement en cours.")),
                ('date_fin', models.DateTimeField(help_text="Fin du cycle d'engagement en cours (se prolonge au renouvellement).")),
                ('date_prochaine_echeance', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.pricingtier')),
                ('societe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='tenants.societe')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(help_text='Abonnement ayant genere cette facture (tracabilite).', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.subscription'),
        ),
    ]
