# Generated by Django 6.1 on 2026-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='marge_tolerance_divergence_litres',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Marge de tolérance (en litres) pour la divergence entre relevé pompiste et relevé Gérant/Chef de piste, au-delà de laquelle une divergence est signalée.', max_digits=6),
        ),
    ]
