# Generated by Django 6.1 on 2026-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_societe_marge_tolerance_divergence_litres'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='seuil_alerte_dette_fcfa',
            field=models.DecimalField(decimal_places=2, default=50000, help_text="Si le solde de dette cumulé d'un pompiste dépasse ce seuil (en FCFA), une alerte est déclenchée pour le pompiste, le Gérant, et l'Admin Siège.", max_digits=12),
        ),
    ]
