# Generated by Django 6.1 on 2026-08-14 22:45

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_societe_seuil_alerte_dette_fcfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de la société, affiché dans l'en-tête des PV de caisse générés. Optionnel — le PV se génère normalement sans logo (nom en texte).", null=True, upload_to=tenants.models.logo_upload_path, validators=[tenants.models.validate_taille_logo]),
        ),
    ]
