# Generated by Django 6.1 on 2026-08-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_societe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='marge_tolerance_ecart_carburant_mensuel_litres',
            field=models.DecimalField(decimal_places=2, default=50, help_text="Marge de tolérance (en litres) pour le cumul mensuel de l'écart carburant (consommé selon les cuves vs vendu selon les pompes). Au-delà, statut Perte/Coulage plutôt que Normal. Distinct de la marge de divergence pompiste/Gérant : nature d'écart différente (stock physique cumulé, pas une erreur de lecture ponctuelle).", max_digits=8),
        ),
    ]
