# Generated by Django 6.1 on 2026-08-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('pompiste', 'Pompiste'), ('chef_de_piste', 'Chef de piste'), ('gerant', 'Gérant'), ('admin_siege', 'Admin Siège')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, help_text="Nulle uniquement pour l'Admin Siège (rôle transversal à toutes les stations de la société).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='stations.station')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
    ]
