# Generated by Django 6.1 on 2026-08-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_tente', models.CharField(help_text='Telephone tente au moment du login', max_length=255)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('reussie', models.BooleanField(default=False)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion (Employe)',
                'verbose_name_plural': 'Tentatives de connexion (Employe)',
                'ordering': ['-date_tentative'],
                'indexes': [models.Index(fields=['identifiant_tente', 'date_tentative'], name='accounts_lo_identif_27da73_idx'), models.Index(fields=['adresse_ip', 'date_tentative'], name='accounts_lo_adresse_5ee306_idx')],
            },
        ),
    ]
