# Generated by Django 6.1 on 2026-08-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_face_employee_affecte_pompe_employee_affecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence')], max_length=10)),
                ('capacite', models.DecimalField(decimal_places=2, help_text='Capacité de stockage de la cuve, en litres', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves', to='stations.station')),
            ],
            options={
                'verbose_name': 'Cuve',
                'verbose_name_plural': 'Cuves',
            },
        ),
    ]
