# Generated by Django 6.1 on 2026-08-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuves', '0001_initial'),
        ('stations', '0002_face_employee_affecte_pompe_employee_affecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité mesurée agrégée (somme de toutes les cuves de ce carburant), en litres', max_digits=10)),
                ('date_jauge', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jauges', to='stations.station')),
            ],
            options={
                'verbose_name': 'Jauge',
                'verbose_name_plural': 'Jauges',
                'ordering': ['-date_jauge'],
                'unique_together': {('station', 'carburant', 'date_jauge')},
            },
        ),
        migrations.CreateModel(
            name='Depotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence')], max_length=10)),
                ('quantite_citerne', models.DecimalField(decimal_places=2, help_text='Quantité mesurée dans la citerne avant dépotage, en litres', max_digits=10)),
                ('date_heure', models.DateTimeField(help_text='Horodatage du dépotage, heure variable')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station')),
                ('jauge_completee', models.ForeignKey(blank=True, help_text='Dernière jauge du même carburant/station juste avant ce dépotage, fixée à la création (jamais recalculée dynamiquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages', to='cuves.jauge')),
            ],
            options={
                'verbose_name': 'Dépotage',
                'verbose_name_plural': 'Dépotages',
                'ordering': ['-date_heure'],
            },
        ),
    ]
