# Generated by Django 6.1 on 2026-08-15 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuves', '0002_jauge_depotage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jauge',
            name='date_mesure',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Moment réel de la mesure physique sur le terrain (modifiable). À utiliser pour tout calcul métier (écart carburant), jamais date_creation.'),
        ),
        migrations.AlterField(
            model_name='jauge',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text="Horodatage technique de la création de l'enregistrement en base (audit uniquement)."),
        ),
    ]
