# Generated by Django 6.1 on 2026-08-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro de la face au sein de la pompe (1 ou 2)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Face',
                'verbose_name_plural': 'Faces',
                'ordering': ['pompe', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro de la pompe au sein de la station')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pompe',
                'verbose_name_plural': 'Pompes',
                'ordering': ['station', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Pistolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, help_text='Numéro séquentiel du pistolet sur toute la station (pas remis à zéro par pompe)')),
                ('carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence')], max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistolets', to='stations.face')),
            ],
            options={
                'verbose_name': 'Pistolet',
                'verbose_name_plural': 'Pistolets',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='face',
            name='pompe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='stations.pompe'),
        ),
        migrations.AddField(
            model_name='pompe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pompes', to='stations.station'),
        ),
        migrations.AlterUniqueTogether(
            name='face',
            unique_together={('pompe', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='pompe',
            unique_together={('station', 'numero')},
        ),
    ]
