# Generated by Django 6.1 on 2026-08-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='employee_affecte',
            field=models.ForeignKey(blank=True, help_text="Affectation au niveau de la face. Exclusif avec l'affectation de toute la pompe.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces_affectees', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='pompe',
            name='employee_affecte',
            field=models.ForeignKey(blank=True, help_text="Affectation au niveau de la pompe entière. Exclusif avec l'affectation par face.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pompes_affectees', to='accounts.employee'),
        ),
    ]
