# Generated by Django 6.1 on 2026-08-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_face_employee_affecte_pompe_employee_affecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence')], max_length=10)),
                ('prix_au_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField(help_text='Date/heure à partir de laquelle ce prix est en vigueur')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_carburants', to='stations.station')),
            ],
            options={
                'verbose_name': 'Prix carburant',
                'verbose_name_plural': 'Prix carburants',
                'ordering': ['-date_debut'],
            },
        ),
    ]
