# Generated by Django 6.1 on 2026-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_prixcarburant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompe',
            name='actif',
        ),
        migrations.AddField(
            model_name='pompe',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='pistolet',
            name='numero',
            field=models.PositiveIntegerField(editable=False, help_text='Numéro séquentiel PAR CARBURANT, sur toute la station (pas remis à zéro par pompe/face — mais chaque carburant a son propre compteur independant, confirme par le terrain). Ex: Gasoil 1, 2, 3... et Essence 1, 2, 3... en parallele.'),
        ),
    ]
