# Generated by Django 6.1 on 2026-08-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0002_face_employee_affecte_pompe_employee_affecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant_encaisse', models.DecimalField(blank=True, decimal_places=2, help_text='Montant réellement encaissé, déclaré par le pompiste à la clôture', max_digits=12, null=True)),
                ('resultat', models.CharField(blank=True, choices=[('manquant', 'Manquant'), ('surplus', 'Surplus')], max_length=10, null=True)),
                ('montant_ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReleveIndexPompiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_releve', models.CharField(choices=[('depart', 'Départ'), ('fin', 'Fin')], max_length=10)),
                ('valeur_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_heure', models.DateTimeField()),
                ('employee', models.ForeignKey(help_text='Le pompiste qui a réalisé ce relevé (capturé au moment du relevé, jamais déduit).', on_delete=django.db.models.deletion.PROTECT, related_name='releves_index_pompiste', to='accounts.employee')),
                ('pistolet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_pompiste', to='stations.pistolet')),
                ('session_caisse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='releves_pompiste', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': "Relevé d'index (pompiste)",
                'verbose_name_plural': "Relevés d'index (pompiste)",
                'ordering': ['date_heure'],
            },
        ),
        migrations.CreateModel(
            name='ReleveIndexGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_releve', models.CharField(choices=[('depart', 'Départ'), ('fin', 'Fin')], max_length=10)),
                ('valeur_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_heure', models.DateTimeField()),
                ('employee', models.ForeignKey(help_text='Le Gérant ou Chef de piste qui a réalisé ce relevé (le vérificateur).', on_delete=django.db.models.deletion.PROTECT, related_name='releves_index_gerant', to='accounts.employee')),
                ('employee_pompiste', models.ForeignKey(help_text='Le pompiste dont les index sont vérifiés par ce relevé (capturé explicitement, jamais déduit).', on_delete=django.db.models.deletion.PROTECT, related_name='releves_verifies_par_gerant', to='accounts.employee')),
                ('pistolet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_gerant', to='stations.pistolet')),
                ('session_caisse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='releves_gerant', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': "Relevé d'index (Gérant/Chef de piste)",
                'verbose_name_plural': "Relevés d'index (Gérant/Chef de piste)",
                'ordering': ['date_heure'],
            },
        ),
    ]
