# Generated by Django 6.1 on 2026-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='divergence_signalee',
            field=models.BooleanField(default=False, help_text="Vrai si l'écart gasoil ou essence dépasse la marge de tolérance de la société. Signalement uniquement, ne bloque jamais la clôture."),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='ecart_essence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Écart en litres entre relevé pompiste et relevé Gérant/Chef de piste, pour l'essence.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='ecart_gasoil',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Écart en litres entre relevé pompiste et relevé Gérant/Chef de piste, pour le gasoil.', max_digits=10, null=True),
        ),
    ]
