# Generated by Django 6.1 on 2026-08-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('caisse', '0002_sessioncaisse_divergence_signalee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldePompiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_courant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_pompiste', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Solde pompiste',
                'verbose_name_plural': 'Soldes pompistes',
            },
        ),
        migrations.CreateModel(
            name='EcritureSolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecriture', models.CharField(choices=[('surplus_constate', 'Surplus constaté'), ('manquant_constate', 'Manquant constaté'), ('ajustement_manuel', 'Ajustement manuel')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text="Toujours positif. Le signe de l'effet se déduit du type_ecriture.", max_digits=12)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('session_caisse', models.ForeignKey(blank=True, help_text="Session de caisse à l'origine de cette écriture. Nulle pour un ajustement manuel.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_solde', to='caisse.sessioncaisse')),
                ('solde_pompiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='caisse.soldepompiste')),
            ],
            options={
                'verbose_name': 'Écriture de solde',
                'verbose_name_plural': 'Écritures de solde',
                'ordering': ['-date_creation'],
            },
        ),
    ]
