# Generated by Django 6.1 on 2026-08-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('caisse', '0003_soldepompiste_ecrituresolde'),
        ('stations', '0003_prixcarburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncaisse',
            name='resultat',
            field=models.CharField(blank=True, choices=[('manquant', 'Manquant'), ('surplus', 'Surplus'), ('exact', 'Exact')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DepenseCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(help_text="Texte libre — pas de catégories prédéfinies pour l'instant.", max_length=255)),
                ('date_heure', models.DateTimeField(help_text='Moment réel de la dépense (modifiable). À ne jamais confondre avec date_creation.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Horodatage technique de la saisie en base (audit uniquement).')),
                ('employee', models.ForeignKey(help_text='Le Gérant ou Chef de piste qui a enregistré la dépense.', on_delete=django.db.models.deletion.PROTECT, related_name='depenses_caisse', to='accounts.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_caisse', to='stations.station')),
            ],
            options={
                'verbose_name': 'Dépense de caisse',
                'verbose_name_plural': 'Dépenses de caisse',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='DepotBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('banque', models.CharField(help_text='Nom de la banque/agence.', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Numéro de reçu, optionnel.', max_length=100)),
                ('date_heure', models.DateTimeField(help_text='Moment réel du dépôt (modifiable). À ne jamais confondre avec date_creation.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Horodatage technique de la saisie en base (audit uniquement).')),
                ('employee', models.ForeignKey(help_text='Le Gérant qui a effectué le dépôt.', on_delete=django.db.models.deletion.PROTECT, related_name='depots_bancaires', to='accounts.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_bancaires', to='stations.station')),
            ],
            options={
                'verbose_name': 'Dépôt bancaire',
                'verbose_name_plural': 'Dépôts bancaires',
                'ordering': ['-date_heure'],
            },
        ),
    ]
