# Generated by Django 6.1 on 2026-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_alter_sessioncaisse_resultat_depensecaisse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des paiements en espèces, incrémenté par le pompiste en cours de service.', max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_orange_money',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des paiements Orange Money, incrémenté par le pompiste en cours de service.', max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_wave',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des paiements Wave, incrémenté par le pompiste en cours de service.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme automatique de montant_cash + montant_wave + montant_orange_money à la clôture. Pas une saisie manuelle unique.', max_digits=12, null=True),
        ),
    ]
