# Generated by Django 6.1 on 2026-08-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattemptemployee'),
        ('caisse', '0005_sessioncaisse_montant_cash_and_more'),
        ('stations', '0003_prixcarburant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='releveindexgerant',
            unique_together={('employee_pompiste', 'pistolet', 'type_releve', 'session_caisse')},
        ),
    ]
