# Generated by Django 6.1 on 2026-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_alter_releveindexgerant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='ecart_montant_pompiste_gerant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Écart entre montant_encaisse (déclaration pompiste) et montant_verse_gerant (vérification Gérant). Signalement uniquement, jamais un blocage.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='litres_essence_vendus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='litres_gasoil_vendus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_theorique_essence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_theorique_gasoil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_theorique_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='montant_verse_gerant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant physiquement compté et vérifié par le Gérant/Chef de piste (vérification indépendante, symétrique à celle des index). FAIT FOI pour le calcul MANQUANT/SURPLUS, pas montant_encaisse.', max_digits=12, null=True),
        ),
    ]
